-- ADD CATEGORY_ID TO PROMOTIONS AND DISCOUNTS
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES categories(id);
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES categories(id);
